### ISSUE TITLE
Como um funcionário administrativo eu quero reservar cargas para serem entregues ao destino através de navios.

### ISSUE THREAD

**Issue by YtaloGabriel** [YtaloGabriel/RastreadorDeCarga-Front-Time2#1]
Aqui deverá ficar a checklist de tarefas

**Comment by MarceloMelo2018** [comment]
**- Front-end**

- [x] Cadastrar cargas;
- [x] Puxar lista de Portos;

**- Back-end:**

- [x] Criar uma lista de portos na Api;
- [x] Mudar o tipo do campo Data_Entrega para o tipo Date (Remover o horário);
- [x] Remover Array do JSON da psquisa por carga única (Exemplo na imagem Refatoracão de cargas);
- [x] Refatorar o campo Status para um Array de Objetos. Cada Objeto deverá conter o campo Data e Localização;

Exemplos: 

Lista de Portos:

![Image](https://user-images.githubusercontent.com/44735202/206946664-d9cde229-551b-42d2-aa66-5c2b573a4b74.png)

Refatoracão de cargas:

![Image](https://user-images.githubusercontent.com/44735202/206946139-bd5d66fd-7f6a-4cd9-b2ef-eca10b8a67f8.png)
