### ISSUE TITLE
Como um usuário comum, eu quero saber a localização atual da minha carga e o status, para que eu possa acompanhar a entrega.

### ISSUE THREAD

**Issue by YtaloGabriel** [YtaloGabriel/RastreadorDeCarga-Front-Time2#4]

**Comment by MarceloMelo2018** [comment]
Implementação da Linha do tempo das cargas, concluída!

Através da Linha do tempo, o usuário pode visualizar toda a trajetoria da carga, desde da sua origem até o seu destino final.
